#服务发现注册配置
server:
  port: 8083
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
spring:
  application:
    name: service-hello