
#服务发现注册配置
server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
spring:
    application:
        name: config-server
    #配置中心相关配置
    cloud:
      config:
        label: master
        server:
          git:
            uri: https://github.com/my-mark/
            search-paths: RainCloud
            username:
            password:
